version: '3'
services:
  # Frontend service
  frontend:
    build:
      context: .
      dockerfile: frontend.dockerfile
    container_name: frontend
    restart: always
    environment:
      - NODE_ENV=${NODE_ENV}
      - JWT_SECRET=${JWT_SECRET}
    expose:
      - "3000"  # Only expose port 3000 within the Docker network

  # Nginx reverse proxy for HTTP (and HTTPS later if needed)
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"       # Expose HTTP on port 80
      - "443:443"     # Placeholder for HTTPS on port 443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # Mount Nginx config
      - /etc/letsencrypt:/etc/letsencrypt         # Mount Let's Encrypt SSL directory

















