version: '2'

services:
  # Nginx reverse proxy for handling frontend requests
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html

  # Let's Encrypt companion for automatic SSL certificates
  nginx-proxy-acme:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    restart: always
    volumes_from:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./acme:/etc/acme.sh
    environment:
      - DEFAULT_EMAIL=${DEFAULT_EMAIL}

  # Frontend service (Next.js)
  frontend:
    build:
      context: .  # Use the Dockerfile in the current directory for building the frontend
      dockerfile: frontend.dockerfile
    container_name: frontend
    restart: always
    environment:
      - VIRTUAL_HOST=${FRONTEND_DOMAIN}
      - LETSENCRYPT_HOST=${FRONTEND_DOMAIN}
    expose:
      - "3000"  # Expose the Next.js port internally



